part of 'core.dart';

/// {@template asset_type}
///
/// All needed types of assets for the Cherry application.
///
/// {@endtemplate}

enum AssetType {
  // Values

  /// {@template asset_type_image}
  ///
  /// The asset is a image.
  ///
  /// {@endtemplate}
  image(
    couldBeUserGenerated: true,
  ),

  /// {@template asset_type_icon}
  ///
  /// The asset is an icon.
  ///
  /// {@endtemplate}
  icon(
    couldBeUserGenerated: false,
  ),

  /// {@template asset_type_video}
  ///
  /// The asset is a video.
  ///
  /// {@endtemplate}
  video(
    couldBeUserGenerated: true,
  ),

  /// {@template asset_type_undefined}
  ///
  /// The asset is undefined.
  ///
  /// {@endtemplate}
  undefined(
    couldBeUserGenerated: null,
  );

  // Static Methods

  /// {@template asset_type_is_generated_by_user}
  ///
  /// Checks if the asset is generated by the user.
  ///
  /// {@endtemplate}
  static Future<bool> isGeneratedByUser([
    String assetPath = CherryRoute.assetsRoute,
  ]) async =>
      await _isGeneratedByUser(assetPath);

  static Future<bool> _isGeneratedByUser([
    String assetPath = CherryRoute.assetsRoute,
  ]) async {
    final mainDirectory = Directory(assetPath);
    if (assetPath == CherryRoute.assetsRoute) {
      return false;
    }
    try {
      await for (final file in mainDirectory.list()) {
        if (file is File && file.path == assetPath) return true;
      }
    } catch (e) {
      return false;
    }
    return false;
  }

  // Properties

  /// {@template asset_type_could_be_user_generated}
  ///
  /// Sets, if the asset could be generated by the user externally.
  ///
  /// {@endtemplate}
  final bool? couldBeUserGenerated;

  // Constructor

  @internal

  /// {@macro asset_type}
  const AssetType({
    required this.couldBeUserGenerated,
  });
}
